
TARGET_OBJS := $(sources-y:.c=.o)
TARGET_AR   := lib$(library_name).a
TARGET_SO   := lib$(library_name).so
TARGET_MK   := lib$(library_name).auto.mk
TARGET_PC   := $(library_name).pc

libs-y   += $(shell $(PKG_CONFIG_CMD) --libs   $(pkgconfig-y))
cflags-y += $(shell $(PKG_CONFIG_CMD) --cflags $(pkgconfig-y)) \
            $(addprefix -I,$(includes-y)) \
            -DPIXMAP_DIR=\"$(CONFIG_PIXMAP_DIR)\"

LIBS   += $(libs-y)   $(libs-priv-y)
CFLAGS += $(cflags-y) $(cflags-priv-y)

export_CFLAGS += $(cflags-y)
export_LIBS   += -L$(shell pwd) -l$(library_name) $(libs-y)

all:	$(TARGET_AR) $(TARGET_MK)

clean:
	@find -name "*.o" -delete
	@find -name "*.a" -delete
	@rm -f $(TARGET_AR) $(TARGET_SO) $(TARGET_MK)

$(TARGET_AR):	$(TARGET_OBJS)
	$(AR) crD $@ $(TARGET_OBJS)

$(TARGET_MK):
	@( echo "# autogenerated" ; \
	  echo "lib_$(library_name)_LIBS=$(export_LIBS)" ; \
	  echo "lib_$(library_name)_CFLAGS=$(export_CFLAGS)" ; \
	  ) > $@

install:

dump:
	@echo "Library target: $(library_name)"
	@echo "LIBS=$(LIBS)"
	@echo "CFLAGS=$(CFLAGS)"
	@echo "TARGET_AR=$(TARGET_AR)"
	@echo "TARGET_SO=$(TARGET_SO)"
	@echo "TARGET_OBJS=$(TARGET_OBJS)"
