
src_root = ..
src_dir = test

include $(src_root)/config.mk
include $(src_root)/mk/pathes.mk
-include $(src_root)/src/libtwtk.auto.mk

prog_name = twtk_test

sources-y += twtk_test.c

include $(src_root)/mk/prog.mk

install:
